Algoritmo "pseudocodigo11"
// Disciplina   :PA
// Professor   : Edilma Binda
// Descrição   : Reais em Dolars
// Autor(a)    : Matheus R. Soares
// Data atual  : 30/03/2023
Var
dolar,cotacao,reais:real


Inicio
escreval("Informe a cotação do dolar:")
leia(cotacao)
escreval("Quantos reais você quer que converta:")
leia(reais)
dolar <- reais/cotacao
escreval("Você tem ",dolar," dolares")


Fimalgoritmo