Algoritmo "Atividade PA 4"
// Disciplina   :PA
// Professor   : Edilma Binda
// Aluno(a)    : Matheus Soares
// Data atual  : 09/03/2023
Var
media,distancia,combustivel:real
Inicio
escreval("Informe a distancia total que o seu automovel percorre:")
leia(distancia)
escreval("Informe o total de combustivel que o seu automovel gasta:")
leia(combustivel)
media <- distancia/combustivel
escreval("O seu automovel gasta em média ",media," litros")
Fimalgoritmo