Algoritmo "Atividade PA 9"
// Disciplina   :PA
// Professor   : Edilma Binda
// Aluno(a)    : Matheus Soares
// Data atual  : 09/03/2023
Var
dolar,cotacao,reais:real
Inicio
escreval("Informe a quantidade de Dolares que você possui:")
leia(dolar)
escreval("Informe qual é o valor da cotação do Dolar nos dias de hoje:")
leia(cotacao)
reais <- dolar * cotacao
escreval("Você possui aproximadamente",reais," reais ")
Fimalgoritmo