Algoritmo "algoritmo"
// Disciplina   : PA
// Professor   : Edilma Binda
// Aluno(a)    : Matheus R Soares
// Data atual  : 25/05/2023
Var
num:real


Inicio
escreval("Defina um numero:")
leia(num)

se (num > 100) e (num < 200) entao
escreval("O seu numero esta em um intervalo entre 100 e 200")
senao
escreval("O seu numero não esta em um intervalo entre 100 e 200")
fimse

Fimalgoritmo
